#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
hours=0
minutes=1
count=0

while [ $hours -lt 12 ] && [ $count -lt 70 ]
do
    echo "Hour: $hours"
    while [ $minutes -lt 60 ] && [ $count -lt 70 ]
    do
        echo $minutes
        minutes=$(( minutes + 1 ))
        count=$(( count + 1 ))
    done
    hours=$(( hours + 1 ))
    minutes=1
done
