#!/usr/bin/env bash
# displays The content of the current directory
for file in *
do
    if [[ -f $file && ! $file == .* ]]
    then
        filename=$(basename "$file")
        suffix="${filename#*-}"
        echo "$suffix"
    fi
done
